---
  # Install supervisor

- name: Install supervisor
  apt: pkg={{ item }} state=installed
  with_items:
  - supervisor
  notify: restart supervisor
  tags: setup

- name: Ensure supervisor config for app
  template: src=supervisor.conf.j2 dest=/etc/supervisor/conf.d/{{ flaskapp_app_name }}.conf
  notify: restart supervisor
  tags: setup

- name: Ensure all supervisor applications are present
  supervisorctl: name="{{ flaskapp_app_supervisor_group }}:" state=present
  tags: setup